### GET
http://localhost/projek-akhir-prakweb-2022-1/api/cart.php?function=get_cart&id=2

### GET BY ID MENU
http://localhost/projek-akhir-prakweb-2022-1/api/cart.php?function=get_cart_id&id_menu=2&id_user=1

### UPDATE QTY
http://localhost/projek-akhir-prakweb-2022-1/api/cart.php?function=update_qty&id=1
Content-Type: application/json

{
  "id_menu": 1,
  "id_user": 2,
  "qty": 5
}

### PURGE
http://localhost/projek-akhir-prakweb-2022-1/api/cart.php?function=purge_cart&id_user=2