############# MENU #############
### GET
http://localhost/olive-chicken/api/order.php?function=get_order

### GET BY ID
http://localhost/olive-chicken/api/order.php?function=get_order_id&id_user=5

### GET TRANSACTION BY ID
http://localhost/olive-chicken/api/order.php?function=get_transaction_id&id_order=42

### POST ORDER
http://localhost/olive-chicken/api/order.php?function=add_order
Content-Type: application/json;

{
  "id_user": 5
}

### POST TRANSACTION
http://localhost/olive-chicken/api/order.php?function=add_transaction
Content-Type: application/json;

{
  "id_order": 24,
  "id_menu": 9,
  "qty": 12
}

### DELETE
http://localhost/olive-chicken/api/menu.php?function=delete_menu&id=5