############# MENU #############
### GET
http://localhost/olive-chicken-delivery/api/menu.php?function=get_menu

### GET BY ID
http://localhost/olive-chicken-delivery/api/menu.php?function=get_menu_id&id=4

### POST ORDER
http://localhost/olive-chicken-delivery/api/order.php?function=add_order
Content-Type: application/json;

{
  "id_user": 5
}

### POST TRANSACTION
http://localhost/olive-chicken-delivery/api/order.php?function=add_transaction
Content-Type: application/json;

{
  "id_order": 24,
  "id_menu": 9,
  "qty": 12
}

### DELETE
http://localhost/olive-chicken-delivery/api/menu.php?function=delete_menu&id=5