### USER
### GET USER
http://localhost/olive-chicken/api/user.php?function=get_user

### GET USER ID
http://localhost/olive-chicken/api/user.php?function=get_user_id&id=2

### GET USER USERNAME
http://localhost/olive-chicken/api/user.php?function=get_user_username&username=plirapli

### GET STATUS
http://localhost/olive-chicken/api/status.php?function=get_status

### POST USER
http://localhost/olive-chicken/api/user.php?function=add_user
Content-Type: application/json;

{
  "nama": "Komang Yuda Saputra",
  "email": "komyud@komyud",
  "username": "komyud",
  "password": "12345678",
  "id_role": 2
}

### EDIT USER
http://localhost/olive-chicken/api/user.php?function=edit_user&id=8
Content-Type: application/json;

{
  "nama": "Muhammad Rafli",
  "email": "rafli@rafli",
  "username": "plirapli",
  "password": "123210078",
  "img_profile": "",
  "telp": "0812312312",
  "id_role": 2
}

### DELETE USER
http://localhost/olive-chicken/api/user.php?function=delete_user&id=6

### ROLE
### GET ROLE
http://localhost/olive-chicken/api/role.php?function=get_role

### GET USER TOTAL GROUP BY ROLE
http://localhost/olive-chicken/api/role.php?function=get_role_total

### DASHBOARD
### GET
http://localhost/olive-chicken/api/total.php?function=get_total


