### GET USER
http://localhost/olive-chicken-delivery/api/user.php?function=get_user

### GET USER ID
http://localhost/olive-chicken-delivery/api/user.php?function=get_user_id&id=2


### GET ROLE
http://localhost/olive-chicken-delivery/api/role.php?function=get_role

### POST USER
http://localhost/olive-chicken-delivery/api/user.php?function=add_user
Content-Type: application/json;

{
  "nama": "Komang Yuda Saputra",
  "email": "komyud@komyud",
  "username": "komyud",
  "password": "12345678",
  "id_role": 2
}

### EDIT USER
http://localhost/olive-chicken-delivery/api/user.php?function=edit_user&id=8
Content-Type: application/json;

{
  "nama": "Komang Yuda S",
  "email": "komyud@yud",
  "username": "komyuds",
  "password": "123210078",
  "img_profile": "",
  "telp": "0812312312",
  "id_role": 3
}


### DELETE USER
http://localhost/olive-chicken-delivery/api/user.php?function=delete_user&id=6